#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SortWindowCtrl2

#include "Basic.hpp"

#include "BP_SortWindowCtrl2_classes.hpp"
#include "BP_SortWindowCtrl2_parameters.hpp"


namespace SDK
{

// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.MouseInputEvent__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORTWINDOW_MOUSE_EVENT_TYPE           MouseEventType                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectListIdx                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectSlotIdx                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ListDrawOffset                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::MouseInputEvent__DelegateSignature(E_SORTWINDOW_MOUSE_EVENT_TYPE MouseEventType, int32 SelectListIdx, int32 SelectSlotIdx, int32 ListDrawOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "MouseInputEvent__DelegateSignature");

	Params::BP_SortWindowCtrl2_C_MouseInputEvent__DelegateSignature Parms{};

	Parms.MouseEventType = MouseEventType;
	Parms.SelectListIdx = SelectListIdx;
	Parms.SelectSlotIdx = SelectSlotIdx;
	Parms.ListDrawOffset = ListDrawOffset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ExecuteUbergraph_BP_SortWindowCtrl2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::ExecuteUbergraph_BP_SortWindowCtrl2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ExecuteUbergraph_BP_SortWindowCtrl2");

	Params::BP_SortWindowCtrl2_C_ExecuteUbergraph_BP_SortWindowCtrl2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_MoveCursor_Up
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_MoveCursor_Up(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_MoveCursor_Up");

	Params::BP_SortWindowCtrl2_C_BPI_MoveCursor_Up Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_MoveCursor_Down
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_MoveCursor_Down(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_MoveCursor_Down");

	Params::BP_SortWindowCtrl2_C_BPI_MoveCursor_Down Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_Page_UP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_Page_UP(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_Page_UP");

	Params::BP_SortWindowCtrl2_C_BPI_Page_UP Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_Page_Down
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_Page_Down(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_Page_Down");

	Params::BP_SortWindowCtrl2_C_BPI_Page_Down Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_MoveCursor_Top
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_MoveCursor_Top(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_MoveCursor_Top");

	Params::BP_SortWindowCtrl2_C_BPI_MoveCursor_Top Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_MoveCursor_Bottom
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_MoveCursor_Bottom(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_MoveCursor_Bottom");

	Params::BP_SortWindowCtrl2_C_BPI_MoveCursor_Bottom Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_OpenWindow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORT_WINDOW_SORT_TYPE                 InSortScene                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_SORTWINDOW_POS_TYPE                   InPosType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsSkipAnimation                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsAutoSetupCursor                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsAutoSetupDecideSlot                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_OpenWindow(E_SORT_WINDOW_SORT_TYPE InSortScene, E_SORTWINDOW_POS_TYPE InPosType, bool IsSkipAnimation, bool IsAutoSetupCursor, bool IsAutoSetupDecideSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_OpenWindow");

	Params::BP_SortWindowCtrl2_C_BPI_OpenWindow Parms{};

	Parms.InSortScene = InSortScene;
	Parms.InPosType = InPosType;
	Parms.IsSkipAnimation = IsSkipAnimation;
	Parms.IsAutoSetupCursor = IsAutoSetupCursor;
	Parms.IsAutoSetupDecideSlot = IsAutoSetupDecideSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_SetCursorAndOffsetIdx
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InListIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InScrollOffset                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsInitSetting                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_SetCursorAndOffsetIdx(int32 InListIndex, int32 InScrollOffset, bool IsInitSetting, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_SetCursorAndOffsetIdx");

	Params::BP_SortWindowCtrl2_C_BPI_SetCursorAndOffsetIdx Parms{};

	Parms.InListIndex = InListIndex;
	Parms.InScrollOffset = InScrollOffset;
	Parms.IsInitSetting = IsInitSetting;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_CloseWindow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSkipAnimation                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_CloseWindow(bool IsSkipAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_CloseWindow");

	Params::BP_SortWindowCtrl2_C_BPI_CloseWindow Parms{};

	Parms.IsSkipAnimation = IsSkipAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_SetCursorAndOffsetPattern
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InListIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_SORTWINDOW_SCROLL_OFFSET_PATTERN      InScrollOffsetPattern                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsInitSetting                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_SetCursorAndOffsetPattern(int32 InListIndex, E_SORTWINDOW_SCROLL_OFFSET_PATTERN InScrollOffsetPattern, bool IsInitSetting, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_SetCursorAndOffsetPattern");

	Params::BP_SortWindowCtrl2_C_BPI_SetCursorAndOffsetPattern Parms{};

	Parms.InListIndex = InListIndex;
	Parms.InScrollOffsetPattern = InScrollOffsetPattern;
	Parms.IsInitSetting = IsInitSetting;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_SetDecideSlot
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InListIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsSave_SortSetting                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsSave_SortOrder                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_SetDecideSlot(int32 InListIndex, const bool IsSave_SortSetting, const bool IsSave_SortOrder, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_SetDecideSlot");

	Params::BP_SortWindowCtrl2_C_BPI_SetDecideSlot Parms{};

	Parms.InListIndex = InListIndex;
	Parms.IsSave_SortSetting = IsSave_SortSetting;
	Parms.IsSave_SortOrder = IsSave_SortOrder;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ReceiveTick");

	Params::BP_SortWindowCtrl2_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ReceiveEndPlay");

	Params::BP_SortWindowCtrl2_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.AddToScreenWidget
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::AddToScreenWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "AddToScreenWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SortWindowCtrl2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_SetMouseHitVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableMouseHit                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_SetMouseHitVisibility(bool EnableMouseHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_SetMouseHitVisibility");

	Params::BP_SortWindowCtrl2_C_BPI_SetMouseHitVisibility Parms{};

	Parms.EnableMouseHit = EnableMouseHit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_ScrollList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InScrollNum                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_ScrollList(int32 InScrollNum, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_ScrollList");

	Params::BP_SortWindowCtrl2_C_BPI_ScrollList Parms{};

	Parms.InScrollNum = InScrollNum;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_CheckMouseWheel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_CheckMouseWheel(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_CheckMouseWheel");

	Params::BP_SortWindowCtrl2_C_BPI_CheckMouseWheel Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_HideDecideSlot
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::BPI_HideDecideSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_HideDecideSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.Init
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.OpenSortWindow
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORT_WINDOW_SORT_TYPE                 InSortScene                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_SORTWINDOW_POS_TYPE                   InPosType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsSkipAnimaiton                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsAutoSetupCursorPos                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsAutoSetupDecideSlot                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::OpenSortWindow(E_SORT_WINDOW_SORT_TYPE InSortScene, E_SORTWINDOW_POS_TYPE InPosType, bool IsSkipAnimaiton, bool IsAutoSetupCursorPos, bool IsAutoSetupDecideSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "OpenSortWindow");

	Params::BP_SortWindowCtrl2_C_OpenSortWindow Parms{};

	Parms.InSortScene = InSortScene;
	Parms.InPosType = InPosType;
	Parms.IsSkipAnimaiton = IsSkipAnimaiton;
	Parms.IsAutoSetupCursorPos = IsAutoSetupCursorPos;
	Parms.IsAutoSetupDecideSlot = IsAutoSetupDecideSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.CloseSortWindow
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSkipAnimation                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::CloseSortWindow(bool IsSkipAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "CloseSortWindow");

	Params::BP_SortWindowCtrl2_C_CloseSortWindow Parms{};

	Parms.IsSkipAnimation = IsSkipAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.End
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ResetParam
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::ResetParam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ResetParam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.UpdateScrollBarRate
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::UpdateScrollBarRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "UpdateScrollBarRate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.UpdateWidgetInfo
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsUpdateText                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsUpdateScrollBar                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsUpdateCursorSlot                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsUpdateDecideSlot                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::UpdateWidgetInfo(bool IsUpdateText, bool IsUpdateScrollBar, bool IsUpdateCursorSlot, bool IsUpdateDecideSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "UpdateWidgetInfo");

	Params::BP_SortWindowCtrl2_C_UpdateWidgetInfo Parms{};

	Parms.IsUpdateText = IsUpdateText;
	Parms.IsUpdateScrollBar = IsUpdateScrollBar;
	Parms.IsUpdateCursorSlot = IsUpdateCursorSlot;
	Parms.IsUpdateDecideSlot = IsUpdateDecideSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.UpdateHelpMessage
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::UpdateHelpMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "UpdateHelpMessage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.UpdateBtnHelp
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInitSetting                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::UpdateBtnHelp(bool IsInitSetting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "UpdateBtnHelp");

	Params::BP_SortWindowCtrl2_C_UpdateBtnHelp Parms{};

	Parms.IsInitSetting = IsInitSetting;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ClampCursorAndOffset
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InCursor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InOffset                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ClampCursor                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ClampOffset                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::ClampCursorAndOffset(int32 InCursor, int32 InOffset, int32* ClampCursor, int32* ClampOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ClampCursorAndOffset");

	Params::BP_SortWindowCtrl2_C_ClampCursorAndOffset Parms{};

	Parms.InCursor = InCursor;
	Parms.InOffset = InOffset;

	UObject::ProcessEvent(Func, &Parms);

	if (ClampCursor != nullptr)
		*ClampCursor = Parms.ClampCursor;

	if (ClampOffset != nullptr)
		*ClampOffset = Parms.ClampOffset;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.SetScrollOffsetPattern
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORTWINDOW_SCROLL_OFFSET_PATTERN      InOffsetPattern                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::SetScrollOffsetPattern(E_SORTWINDOW_SCROLL_OFFSET_PATTERN InOffsetPattern)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "SetScrollOffsetPattern");

	Params::BP_SortWindowCtrl2_C_SetScrollOffsetPattern Parms{};

	Parms.InOffsetPattern = InOffsetPattern;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.GetSlotDrawNum
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   SlotNum                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::GetSlotDrawNum(int32* SlotNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "GetSlotDrawNum");

	Params::BP_SortWindowCtrl2_C_GetSlotDrawNum Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SlotNum != nullptr)
		*SlotNum = Parms.SlotNum;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.SetCursorAndOffsetIdx
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InListIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InScrollOffset                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsInitSetting                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::SetCursorAndOffsetIdx(int32 InListIndex, int32 InScrollOffset, bool IsInitSetting, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "SetCursorAndOffsetIdx");

	Params::BP_SortWindowCtrl2_C_SetCursorAndOffsetIdx Parms{};

	Parms.InListIndex = InListIndex;
	Parms.InScrollOffset = InScrollOffset;
	Parms.IsInitSetting = IsInitSetting;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.SetCursorAndOffsetPattern
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InListIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_SORTWINDOW_SCROLL_OFFSET_PATTERN      InScrollOffsetPattern                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsInitSetting                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::SetCursorAndOffsetPattern(int32 InListIndex, E_SORTWINDOW_SCROLL_OFFSET_PATTERN InScrollOffsetPattern, bool IsInitSetting, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "SetCursorAndOffsetPattern");

	Params::BP_SortWindowCtrl2_C_SetCursorAndOffsetPattern Parms{};

	Parms.InListIndex = InListIndex;
	Parms.InScrollOffsetPattern = InScrollOffsetPattern;
	Parms.IsInitSetting = IsInitSetting;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.CursorMove_Up
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::CursorMove_Up(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "CursorMove_Up");

	Params::BP_SortWindowCtrl2_C_CursorMove_Up Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.CursorMove_Down
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::CursorMove_Down(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "CursorMove_Down");

	Params::BP_SortWindowCtrl2_C_CursorMove_Down Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.CursorMove_Top
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::CursorMove_Top(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "CursorMove_Top");

	Params::BP_SortWindowCtrl2_C_CursorMove_Top Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.CursorMove_Bottom
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::CursorMove_Bottom(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "CursorMove_Bottom");

	Params::BP_SortWindowCtrl2_C_CursorMove_Bottom Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.Page_Up
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::Page_Up(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "Page_Up");

	Params::BP_SortWindowCtrl2_C_Page_Up Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.Page_Down
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::Page_Down(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "Page_Down");

	Params::BP_SortWindowCtrl2_C_Page_Down Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.SetDecideSlot
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InListIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsSaveSortSetting                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsSaveSortOrder                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::SetDecideSlot(int32 InListIndex, bool IsSaveSortSetting, bool IsSaveSortOrder, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "SetDecideSlot");

	Params::BP_SortWindowCtrl2_C_SetDecideSlot Parms{};

	Parms.InListIndex = InListIndex;
	Parms.IsSaveSortSetting = IsSaveSortSetting;
	Parms.IsSaveSortOrder = IsSaveSortOrder;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.HideDecideSlot
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::HideDecideSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "HideDecideSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.GetDispMaxOffset
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   SlotNum                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::GetDispMaxOffset(int32* SlotNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "GetDispMaxOffset");

	Params::BP_SortWindowCtrl2_C_GetDispMaxOffset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SlotNum != nullptr)
		*SlotNum = Parms.SlotNum;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BindMouseInputEvent
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::BindMouseInputEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BindMouseInputEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.UnbindMouseInputEvent
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_SortWindowCtrl2_C::UnbindMouseInputEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "UnbindMouseInputEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.CheckMouseWheel
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::CheckMouseWheel(bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "CheckMouseWheel");

	Params::BP_SortWindowCtrl2_C_CheckMouseWheel Parms{};

	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.IsEnableMouseWheel
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    IsEnable                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::IsEnableMouseWheel(bool* IsEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "IsEnableMouseWheel");

	Params::BP_SortWindowCtrl2_C_IsEnableMouseWheel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsEnable != nullptr)
		*IsEnable = Parms.IsEnable;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.OnHoveredSlot_ByMouse
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InSlotIdx                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::OnHoveredSlot_ByMouse(int32 InSlotIdx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "OnHoveredSlot_ByMouse");

	Params::BP_SortWindowCtrl2_C_OnHoveredSlot_ByMouse Parms{};

	Parms.InSlotIdx = InSlotIdx;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.OnClickedSlot_ByMouse
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InSlotIdx                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::OnClickedSlot_ByMouse(int32 InSlotIdx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "OnClickedSlot_ByMouse");

	Params::BP_SortWindowCtrl2_C_OnClickedSlot_ByMouse Parms{};

	Parms.InSlotIdx = InSlotIdx;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.OnMovedScrollBar_ByMouse
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InScrollRate                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::OnMovedScrollBar_ByMouse(float InScrollRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "OnMovedScrollBar_ByMouse");

	Params::BP_SortWindowCtrl2_C_OnMovedScrollBar_ByMouse Parms{};

	Parms.InScrollRate = InScrollRate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.ScrollList
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InScrollNum                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsPlaySE                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::ScrollList(int32 InScrollNum, bool IsPlaySE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "ScrollList");

	Params::BP_SortWindowCtrl2_C_ScrollList Parms{};

	Parms.InScrollNum = InScrollNum;
	Parms.IsPlaySE = IsPlaySE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.SetMouseHitVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableMouseHit                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::SetMouseHitVisibility(bool EnableMouseHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "SetMouseHitVisibility");

	Params::BP_SortWindowCtrl2_C_SetMouseHitVisibility Parms{};

	Parms.EnableMouseHit = EnableMouseHit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_GetCursor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ListIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_GetCursor(int32* ListIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_GetCursor");

	Params::BP_SortWindowCtrl2_C_BPI_GetCursor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ListIndex != nullptr)
		*ListIndex = Parms.ListIndex;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_GetAppliedSetting
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORT_WINDOW_SORT_TYPE                 InSortScene                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   AppliedSetting                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_SORT_WINDOW_SORT_ORDER                AppliedOrder                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_GetAppliedSetting(E_SORT_WINDOW_SORT_TYPE InSortScene, int32* AppliedSetting, E_SORT_WINDOW_SORT_ORDER* AppliedOrder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_GetAppliedSetting");

	Params::BP_SortWindowCtrl2_C_BPI_GetAppliedSetting Parms{};

	Parms.InSortScene = InSortScene;

	UObject::ProcessEvent(Func, &Parms);

	if (AppliedSetting != nullptr)
		*AppliedSetting = Parms.AppliedSetting;

	if (AppliedOrder != nullptr)
		*AppliedOrder = Parms.AppliedOrder;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_GetAnimState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORTWINDOW_ANIM_STATE                 AnimState                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_GetAnimState(E_SORTWINDOW_ANIM_STATE* AnimState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_GetAnimState");

	Params::BP_SortWindowCtrl2_C_BPI_GetAnimState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimState != nullptr)
		*AnimState = Parms.AnimState;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_GetDecideSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ListIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_GetDecideSlot(int32* ListIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_GetDecideSlot");

	Params::BP_SortWindowCtrl2_C_BPI_GetDecideSlot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ListIndex != nullptr)
		*ListIndex = Parms.ListIndex;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_GetListNum
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ListNum                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_GetListNum(int32* ListNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_GetListNum");

	Params::BP_SortWindowCtrl2_C_BPI_GetListNum Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ListNum != nullptr)
		*ListNum = Parms.ListNum;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_GetScrollOffset
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ScrollOffset                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_GetScrollOffset(int32* ScrollOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_GetScrollOffset");

	Params::BP_SortWindowCtrl2_C_BPI_GetScrollOffset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ScrollOffset != nullptr)
		*ScrollOffset = Parms.ScrollOffset;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_SetScrollOffsetPattern
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_SORTWINDOW_SCROLL_OFFSET_PATTERN      InOffssetPattern                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ScrollOffset                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SortWindowCtrl2_C::BPI_SetScrollOffsetPattern(E_SORTWINDOW_SCROLL_OFFSET_PATTERN InOffssetPattern, int32* ScrollOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_SetScrollOffsetPattern");

	Params::BP_SortWindowCtrl2_C_BPI_SetScrollOffsetPattern Parms{};

	Parms.InOffssetPattern = InOffssetPattern;

	UObject::ProcessEvent(Func, &Parms);

	if (ScrollOffset != nullptr)
		*ScrollOffset = Parms.ScrollOffset;
}


// Function BP_SortWindowCtrl2.BP_SortWindowCtrl2_C.BPI_IsEnableMouseWheel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnable                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SortWindowCtrl2_C::BPI_IsEnableMouseWheel(bool* IsEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SortWindowCtrl2_C", "BPI_IsEnableMouseWheel");

	Params::BP_SortWindowCtrl2_C_BPI_IsEnableMouseWheel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsEnable != nullptr)
		*IsEnable = Parms.IsEnable;
}

}

