#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StatueLvUp

#include "Basic.hpp"

#include "BP_StatueLvUp_classes.hpp"
#include "BP_StatueLvUp_parameters.hpp"


namespace SDK
{

// Function BP_StatueLvUp.BP_StatueLvUp_C.ExecuteUbergraph_BP_StatueLvUp
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatueLvUp_C::ExecuteUbergraph_BP_StatueLvUp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatueLvUp_C", "ExecuteUbergraph_BP_StatueLvUp");

	Params::BP_StatueLvUp_C_ExecuteUbergraph_BP_StatueLvUp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatueLvUp.BP_StatueLvUp_C.EndStatueEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_StatueLvUp_C::EndStatueEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatueLvUp_C", "EndStatueEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatueLvUp.BP_StatueLvUp_C.QuestExecute
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_StatueLvUp_C::QuestExecute()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatueLvUp_C", "QuestExecute");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatueLvUp.BP_StatueLvUp_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_StatueLvUp_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatueLvUp_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatueLvUp.BP_StatueLvUp_C.CallDeactivate
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_StatueLvUp_C::CallDeactivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatueLvUp_C", "CallDeactivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatueLvUp.BP_StatueLvUp_C.CheckActive
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_StatueLvUp_C::CheckActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatueLvUp_C", "CheckActive");

	UObject::ProcessEvent(Func, nullptr);
}

}

