#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CharaStatus

#include "Basic.hpp"

#include "BPI_CharaStatus_classes.hpp"
#include "BPI_CharaStatus_parameters.hpp"


namespace SDK
{

// Function BPI_CharaStatus.BPI_CharaStatus_C.EndSwap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TopIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::EndSwap(int32 TopIndex, bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "EndSwap");

	Params::BPI_CharaStatus_C_EndSwap Parms{};

	Parms.TopIndex = TopIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.IsEndSwapSlide
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    End                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::IsEndSwapSlide(bool* End)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "IsEndSwapSlide");

	Params::BPI_CharaStatus_C_IsEndSwapSlide Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (End != nullptr)
		*End = Parms.End;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.SwapRightSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   HoldSlot                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CursorSlot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::SwapRightSlot(int32 HoldSlot, int32 CursorSlot, bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "SwapRightSlot");

	Params::BPI_CharaStatus_C_SwapRightSlot Parms{};

	Parms.HoldSlot = HoldSlot;
	Parms.CursorSlot = CursorSlot;

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.UpdateBiography
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Offset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewOffset                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_CharaStatus_C::UpdateBiography(int32 Offset, int32* NewOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "UpdateBiography");

	Params::BPI_CharaStatus_C_UpdateBiography Parms{};

	Parms.Offset = Offset;

	UObject::ProcessEvent(Func, &Parms);

	if (NewOffset != nullptr)
		*NewOffset = Parms.NewOffset;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.UpdateConditionCursor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TopIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::UpdateConditionCursor(int32 TopIndex, bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "UpdateConditionCursor");

	Params::BPI_CharaStatus_C_UpdateConditionCursor Parms{};

	Parms.TopIndex = TopIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.UpdateSkillSwap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TopIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsHolding                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::UpdateSkillSwap(int32 TopIndex, bool IsHolding, bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "UpdateSkillSwap");

	Params::BPI_CharaStatus_C_UpdateSkillSwap Parms{};

	Parms.TopIndex = TopIndex;
	Parms.IsHolding = IsHolding;

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.ChangePage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::ChangePage(bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "ChangePage");

	Params::BPI_CharaStatus_C_ChangePage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.CloseStatus_Common
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::CloseStatus_Common(bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "CloseStatus_Common");

	Params::BPI_CharaStatus_C_CloseStatus_Common Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.HideUI_Common
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::HideUI_Common(bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "HideUI_Common");

	Params::BPI_CharaStatus_C_HideUI_Common Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.ChangeChara_Common
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MoveLR                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UseLRAnim                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::ChangeChara_Common(int32 MoveLR, bool UseLRAnim, bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "ChangeChara_Common");

	Params::BPI_CharaStatus_C_ChangeChara_Common Parms{};

	Parms.MoveLR = MoveLR;
	Parms.UseLRAnim = UseLRAnim;

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}


// Function BPI_CharaStatus.BPI_CharaStatus_C.OpenStatus_Common
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIStatusCtrlDataObjBase*         StatusCtrlObj                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    WithTitle                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Dummy                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CharaStatus_C::OpenStatus_Common(const class UUIStatusCtrlDataObjBase*& StatusCtrlObj, bool WithTitle, bool* Dummy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CharaStatus_C", "OpenStatus_Common");

	Params::BPI_CharaStatus_C_OpenStatus_Common Parms{};

	Parms.StatusCtrlObj = StatusCtrlObj;
	Parms.WithTitle = WithTitle;

	UObject::ProcessEvent(Func, &Parms);

	if (Dummy != nullptr)
		*Dummy = Parms.Dummy;
}

}

