#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_CAMPTOPCTRL_GSTATUS

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_CAMPTOPCTRL_GSTATUS.E_CAMPTOPCTRL_GSTATUS
// NumValues: 0x0016
enum class E_CAMPTOPCTRL_GSTATUS : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator5                           = 3,
	NewEnumerator6                           = 4,
	NewEnumerator13                          = 5,
	NewEnumerator7                           = 6,
	NewEnumerator8                           = 7,
	NewEnumerator9                           = 8,
	NewEnumerator10                          = 9,
	NewEnumerator3                           = 10,
	NewEnumerator4                           = 11,
	NewEnumerator11                          = 12,
	NewEnumerator12                          = 13,
	NewEnumerator14                          = 14,
	NewEnumerator15                          = 15,
	NewEnumerator16                          = 16,
	NewEnumerator17                          = 17,
	NewEnumerator18                          = 18,
	NewEnumerator19                          = 19,
	NewEnumerator20                          = 20,
	E_CAMPTOPCTRL_MAX                        = 21,
};

}

