#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_MapSymbolLevelDiff

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_MapSymbolLevelDiff.E_MapSymbolLevelDiff
// NumValues: 0x0004
enum class E_MapSymbolLevelDiff : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	E_MAX                                    = 3,
};

}

