#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MM_M061_EM0021_Ready

#include "Basic.hpp"


namespace SDK::Params
{

// Function MM_M061_EM0021_Ready.MM_M061_EM0021_Ready_C.ExecuteUbergraph_MM_M061_EM0021_Ready
// 0x0218 (0x0218 - 0x0000)
struct MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA2D[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetActive_IsActive;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA2E[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UIManager_C>      K2Node_DynamicCast_AsBPI_UIManager;                // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA2F[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UProjectUIManager*                      CallFunc_BPI_GetUIManager_UIManager;               // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UIManager_C>      K2Node_DynamicCast_AsBPI_UIManager_1;              // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA30[0x7];                                     // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BPI_GetMsgCtrl_OutActor;                  // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl;                 // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA31[0x7];                                     // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_1;               // 0x0070(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA32[0x7];                                     // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_2;               // 0x0088(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA33[0x7];                                     // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_3;               // 0x00A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IIsFinishedWindowOut_OutFinished;         // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_StartMapEvent_Dummy;                      // 0x00B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EndMapEvent_Dummy;                        // 0x00B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA34[0x4];                                     // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA35[0x7];                                     // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APla603_C*                              K2Node_DynamicCast_AsPla_603;                      // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA36[0x7];                                     // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue_1;              // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APla603_C*                              K2Node_DynamicCast_AsPla_603_1;                    // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMapActionPlaying_bPlaying;              // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA37[0x2];                                     // 0x00FE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_1;            // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UIManager_C>      K2Node_DynamicCast_AsBPI_UIManager_2;              // 0x0108(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA38[0x7];                                     // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UProjectUIManager*                      CallFunc_BPI_GetUIManager_UIManager_1;             // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMapEventActivateFlags_ReturnValue;      // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA39[0x7];                                     // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_UIManager_C>      K2Node_DynamicCast_AsBPI_UIManager_3;              // 0x0130(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA3A[0x7];                                     // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BPI_GetMsgCtrl_OutActor_1;                // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_4;               // 0x0150(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA3B[0x7];                                     // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_5;               // 0x0168(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IMsgCtrl_GetIsMacroEnd_IsEnd;             // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA3C[0x6];                                     // 0x017A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_2;            // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UIManager_C>      K2Node_DynamicCast_AsBPI_UIManager_4;              // 0x0188(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_12;                    // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA3D[0x7];                                     // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UProjectUIManager*                      CallFunc_BPI_GetUIManager_UIManager_2;             // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_UIManager_C>      K2Node_DynamicCast_AsBPI_UIManager_5;              // 0x01A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_13;                    // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMapEventActivateFlags_ReturnValue_1;    // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA3E[0x6];                                     // 0x01BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BPI_GetMsgCtrl_OutActor_2;                // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_6;               // 0x01C8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_14;                    // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA3F[0x7];                                     // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_7;               // 0x01E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_15;                    // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA40[0x7];                                     // 0x01F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_MsgCtrl_C>        K2Node_DynamicCast_AsBPI_Msg_Ctrl_8;               // 0x01F8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_16;                    // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA41[0x3];                                     // 0x0209(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x020C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA42[0x3];                                     // 0x0211(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0214(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready) == 0x000008, "Wrong alignment on MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready");
static_assert(sizeof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready) == 0x000218, "Wrong size on MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, EntryPoint) == 0x000000, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::EntryPoint' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_GetGameInstance_ReturnValue) == 0x000008, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_GetActive_IsActive) == 0x000010, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_GetActive_IsActive' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_UIManager) == 0x000018, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_UIManager' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BPI_GetUIManager_UIManager) == 0x000030, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BPI_GetUIManager_UIManager' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_UIManager_1) == 0x000038, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_UIManager_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_1) == 0x000048, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BPI_GetMsgCtrl_OutActor) == 0x000050, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BPI_GetMsgCtrl_OutActor' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl) == 0x000058, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_2) == 0x000068, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_1) == 0x000070, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_3) == 0x000080, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_2) == 0x000088, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_2' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_4) == 0x000098, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_3) == 0x0000A0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_3' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_5) == 0x0000B0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IIsFinishedWindowOut_OutFinished) == 0x0000B1, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IIsFinishedWindowOut_OutFinished' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_StartMapEvent_Dummy) == 0x0000B2, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_StartMapEvent_Dummy' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_EndMapEvent_Dummy) == 0x0000B3, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_EndMapEvent_Dummy' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, Temp_int_Array_Index_Variable) == 0x0000B4, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_Array_Length_ReturnValue) == 0x0000B8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_Array_Get_Item) == 0x0000C0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IsValid_ReturnValue) == 0x0000C8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_GetPlayerPawn_ReturnValue) == 0x0000D0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsPla_603) == 0x0000D8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsPla_603' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_6) == 0x0000E0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_GetPlayerPawn_ReturnValue_1) == 0x0000E8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_GetPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsPla_603_1) == 0x0000F0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsPla_603_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_7) == 0x0000F8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_Not_PreBool_ReturnValue) == 0x0000F9, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IsMapActionPlaying_bPlaying) == 0x0000FA, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IsMapActionPlaying_bPlaying' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IsValid_ReturnValue_1) == 0x0000FB, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IsMovingOnGround_ReturnValue) == 0x0000FC, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BooleanAND_ReturnValue) == 0x0000FD, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_GetGameInstance_ReturnValue_1) == 0x000100, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_GetGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_UIManager_2) == 0x000108, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_UIManager_2' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_8) == 0x000118, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BPI_GetUIManager_UIManager_1) == 0x000120, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BPI_GetUIManager_UIManager_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IsMapEventActivateFlags_ReturnValue) == 0x000128, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IsMapEventActivateFlags_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_UIManager_3) == 0x000130, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_UIManager_3' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_9) == 0x000140, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BPI_GetMsgCtrl_OutActor_1) == 0x000148, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BPI_GetMsgCtrl_OutActor_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_4) == 0x000150, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_4' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_10) == 0x000160, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_5) == 0x000168, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_5' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_11) == 0x000178, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_11' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IMsgCtrl_GetIsMacroEnd_IsEnd) == 0x000179, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IMsgCtrl_GetIsMacroEnd_IsEnd' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_GetGameInstance_ReturnValue_2) == 0x000180, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_GetGameInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_UIManager_4) == 0x000188, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_UIManager_4' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_12) == 0x000198, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_12' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BPI_GetUIManager_UIManager_2) == 0x0001A0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BPI_GetUIManager_UIManager_2' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_UIManager_5) == 0x0001A8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_UIManager_5' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_13) == 0x0001B8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_13' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_IsMapEventActivateFlags_ReturnValue_1) == 0x0001B9, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_IsMapEventActivateFlags_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_BPI_GetMsgCtrl_OutActor_2) == 0x0001C0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_BPI_GetMsgCtrl_OutActor_2' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_6) == 0x0001C8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_6' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_14) == 0x0001D8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_14' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_7) == 0x0001E0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_7' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_15) == 0x0001F0, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_15' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_AsBPI_Msg_Ctrl_8) == 0x0001F8, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_AsBPI_Msg_Ctrl_8' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, K2Node_DynamicCast_bSuccess_16) == 0x000208, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::K2Node_DynamicCast_bSuccess_16' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, Temp_int_Loop_Counter_Variable) == 0x00020C, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_Less_IntInt_ReturnValue) == 0x000210, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready, CallFunc_Add_IntInt_ReturnValue) == 0x000214, "Member 'MM_M061_EM0021_Ready_C_ExecuteUbergraph_MM_M061_EM0021_Ready::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

}

