#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TokyoMapPlayer

#include "Basic.hpp"

#include "TokyoMapPlayer_classes.hpp"
#include "TokyoMapPlayer_parameters.hpp"


namespace SDK
{

// Function TokyoMapPlayer.TokyoMapPlayer_C.ExecuteUbergraph_TokyoMapPlayer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATokyoMapPlayer_C::ExecuteUbergraph_TokyoMapPlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "ExecuteUbergraph_TokyoMapPlayer");

	Params::TokyoMapPlayer_C_ExecuteUbergraph_TokyoMapPlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.AreaOut
// (BlueprintCallable, BlueprintEvent)

void ATokyoMapPlayer_C::AreaOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "AreaOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.AreaIN
// (BlueprintCallable, BlueprintEvent)

void ATokyoMapPlayer_C::AreaIN()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "AreaIN");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATokyoMapPlayer_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "ReceiveTick");

	Params::TokyoMapPlayer_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATokyoMapPlayer_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.AreaOutTimeLine__UpdateFunc
// (BlueprintEvent)

void ATokyoMapPlayer_C::AreaOutTimeLine__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "AreaOutTimeLine__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.AreaOutTimeLine__FinishedFunc
// (BlueprintEvent)

void ATokyoMapPlayer_C::AreaOutTimeLine__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "AreaOutTimeLine__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.AreaINTimeLine__UpdateFunc
// (BlueprintEvent)

void ATokyoMapPlayer_C::AreaINTimeLine__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "AreaINTimeLine__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.AreaINTimeLine__FinishedFunc
// (BlueprintEvent)

void ATokyoMapPlayer_C::AreaINTimeLine__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "AreaINTimeLine__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.OnMove
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Force                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATokyoMapPlayer_C::OnMove(bool Force)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "OnMove");

	Params::TokyoMapPlayer_C_OnMove Parms{};

	Parms.Force = Force;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.OnIdle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Force                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATokyoMapPlayer_C::OnIdle(bool Force)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "OnIdle");

	Params::TokyoMapPlayer_C_OnIdle Parms{};

	Parms.Force = Force;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.PlayAnim
// (Public, BlueprintCallable, BlueprintEvent)

void ATokyoMapPlayer_C::PlayAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "PlayAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.ChangeDash
// (Public, BlueprintCallable, BlueprintEvent)

void ATokyoMapPlayer_C::ChangeDash()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "ChangeDash");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TokyoMapPlayer.TokyoMapPlayer_C.ChangeWalk
// (Public, BlueprintCallable, BlueprintEvent)

void ATokyoMapPlayer_C::ChangeWalk()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TokyoMapPlayer_C", "ChangeWalk");

	UObject::ProcessEvent(Func, nullptr);
}

}

